server:
  port: 8094
spring:
  application:
    name: rentals
  data:
    mongodb:
      authentication-database: admin
      username: ${USERNAME}
      password: ${PASSWORD}
      port: ${MONGODB_PORT}
      host: ${MONGODB_HOST}
  config:
    import: optional:file:.env[.properties]

kafka:
  topic: carsharing
  partitions: 10
  replicas: 1
  port: ${KAFKA_PORT}
  key: ${KAFKA_KEY}

